### ISSUE TITLE
Discord channel?

### ISSUE THREAD

**Issue by V4n1X** [miicam/MiiCam#11]
Hello,

here are a few Guys that have knowledge and new ideas, so we can setup a discord channel for free, and do there some Testing. What do you think?

**Comment by fliphess** [comment]
I love it :)

**Comment by fliphess** [comment]
I'll get to it right away ;)

**Comment by fliphess** [comment]
There you go: https://discord.gg/rjW2SSB

I'll add it to the docs in a minute... I'm quite new to discord, open to suggestions :)
