### ISSUE TITLE
Can't boot

### ISSUE THREAD

**Issue by pimoon** [miicam/MiiCam#15]
I followed the instructions but can't make my camera booting and be accessing in local : 
- If I reset the camera and boot with the sd card, the yellow led is flashing indefinitely.
- If I reset the camera and boot without the card, I can configure the wifi through Mi Home app and get fix blue led. But then when I reboot with the SD card I can't access the camera in local with it's own IP, although it is still working with the mi home app.

So I guess my camera don't look at the files on SD card.

Here is the actual firmware, should I upgrade ?
![IMG_0550](https://user-images.githubusercontent.com/46498300/55653762-cb3bb980-57ef-11e9-85c2-479a581662c7.jpeg)

**Comment by pimoon** [comment]
Well after further investigation I think my camera has a problem because it cannot detect the SD card inserted with Mi home app.
I tried with 3 differents SD card, 32Gb and 8Gb. Format in FAT32 under MacOS and Ubuntu.

**Comment by pimoon** [comment]
it's finally a hardware issue.

**Comment by fliphess** [comment]
@pimoon Was it a hardware issue after all or did you manage to get it to work eventually?
