### ISSUE TITLE
Where can i DL tf_recovery.img?

### ISSUE THREAD

**Issue by Zippeyrude** [miicam/MiiCam#27]
I have the latest FW so understand that i need to flash the camera with the tf_recovery.img file.

Is there an approved DL source for this please?

**Comment by fliphess** [comment]
@Zippeyrude [This one](https://github.com/miicam/MiiCam/blob/master/tf_recovery.img) ?

**Comment by Zippeyrude** [comment]
Thank you @fliphess 

I also found one [here](https://drive.google.com/drive/folders/1ci4WnTCL9nsY8CHJkf3rog1Lnl7MO1sx)
