### ISSUE TITLE
Config Editor in Web Interface not working

### ISSUE THREAD

**Issue by V4n1X** [miicam/MiiCam#3]
Hello,

in the latest Version, if I want to change something in the Config over the WebUI, i get when I Save the Config this ERROR:

Invalid input in configuration content: ROOT_PASSWORD='MyPassword123' (line: 28)

Happens even with the default password, also if I change nothing and want to save the config again, this happens.

**Comment by fliphess** [comment]
Hey @V4n1X!

Thanks for reporting this. 

I think it has something to do with the regex that is checked for invalid chars. 
I will have a look at it.

**Comment by fliphess** [comment]
Ah! it's [in the regex](https://github.com/miicam/MiiCamWeb/blob/master/libs/system.php#L108)! 

As a workaround, try using double quotes rather than single, that should work until I've found a way to fix it :)

**Comment by fliphess** [comment]
This should now be live in the next release. Thanks for letting me know! 👍
