### ISSUE TITLE
MJSXJ01CM not conected

### ISSUE THREAD

**Issue by djmalin** [miicam/MiiCam#33]
Hello, I need help, I have uploaded all the files to the card, I entered the password and the network in the config file, but the camera does not want to connect to the network? that's how I got the camera log:
Chuangmi 720P configuration:

  HOSTNAME       = camera
  TIMEZONE       = UTC

################################
*** Mounting newer busybox
*** Enabling logging
*** Stopping logging... OK
*** Starting logging... OK
*** Making /etc writable
*** Mounting /root from sd card
*** Setting up WIFI configuration
*** Configuring WIFI... 
*** Updating WIFI settings based on config.cfg
*** Setting up our own gmlib config
*** Setting root password... 
chpasswd: password for 'root' changed
chpasswd: password for 'admin' changed
*** Configure time zone... 
*** Setting hostname... 
*** Configuring new /etc/hosts file... 
*** Appending /tmp/sd/firmware/etc/hosts to /etc/hosts
*** Replacing restartd startup script and config with our own version
*** Disabling Cloud... 
*** Disabling miio_avstreamer... 
*** Disabling miio_client... 
*** Disabling miio_client_helper_nomqtt.sh... 
*** Disabling miot_devicekit... 
*** Disabling miot_qrcode.sh... 
*** Disabling miio_smb... 
*** Disabling logmi.sh... 
*** Disabling OTA... 
*** Disabling miio_ota... 
*** Executing /mnt/data/test/boot.sh... 
*** Mounting /tmp/sd/firmware/bin on /tmp/sd/ft... 
*** Waiting for ping reply from 8.8.8.8 for 10 times............. FAIL
*** No internet connection detected! Sad panda :(
*** The blue led was turned on
*** The yellow led was set off
*** Setting IR led to 0
*** Restoring led and image settings from /tmp/sd/firmware/etc/restore_state.db
*** ERROR: Statefile /tmp/sd/firmware/etc/restore_state.db not found!
*** Stopping telnetd Telnet Daemon ...
*** Copying previous files to /etc/dropbear... OK
*** Starting dropbear SSH server... 
*** Stopping crond Cron Daemon ...
*** Starting crond Cron Daemon... 
*** Starting ntpd NTP Daemon... 
*** Starting lighttpd web server... 
*** Starting rtspd RTSP server... 
*** Stopping auto_night_mode Auto Night Mode ...
*** Stopping restartd Restartd daemon ...

[ ] - Issue or bug is not in: https://github.com/fliphess/chuangmi-720p-hack/wiki/Troubleshooting)
[ ] - I've attached a log file (https://github.com/fliphess/chuangmi-720p-hack/wiki/How-to-tar-or-zip-the-logs-when-filing-an-issue)

**Describe in the issue you are experiencing, what behaviour you see, if you see any errors and most important if something is not working: send the log files, I really need to see them to help you debug.**
...

**Comment by fliphess** [comment]
@djmalin Try connecting the camera to the wifi using the app first (https://miicam.github.io/Troubleshooting/#wifi-connection-issues)
