### ISSUE TITLE
Support for SXJ01ZM

### ISSUE THREAD

**Issue by testuser7** [miicam/MiiCam#34]
Any chance?
Previous hack is not actively developed anymore: https://github.com/Filipowicz251/mijia-1080P-hacks

**Comment by fliphess** [comment]
Nope! Sorry to say, but I am not able to support hardware that I don't own. 
It might be possible to fork this repository and build on top of it for other camera's but the firmware is quite specific and depending on these specifics I cannot guarantee I won't brick other camera's than the ones I own.
