### ISSUE TITLE
RTMP Microphone / Sound

### ISSUE THREAD

**Issue by V4n1X** [miicam/MiiCam#7]
Hello,
don't know if I am too stupid, but why there is no sound on the rtmp stream.
If that feature is missing, can you implement it?

**Comment by fliphess** [comment]
Hey @V4n1X! :) 

It would be a great enhancement of this toolset, but don't expect it soon...

I'm doing some early experiments with the audio samples in the toolchain, and hopefully from there i can get somewhere using the speaker and the microphone eventually.

There is no documentation or source code for the rtsp library and I'm a starting C coder that has still lots to learn so it's mostly blind guessing until something works :) 

I'm working on a simple tool to play audio on the internal speaker, after that recording from the mic should not be impossible (there are some code samples in the toolchain) and after that I might be able to make some more progress, but combining audio parts and video frames in a network stream using a library without docs or sources is quite another level :)
